Workaround for dynamiske vedleggsIder
navikt/skjemautfylling-formio pull request #79
Opened 2020-10-28 11:38 UTC by 7er

2020-10-28 11:50 UTC, sisselfladby approved these changes
Fint dette! Burde vi hatt en test her kanskje? :)

2020-10-28 11:50 UTC, wen7i commented on src/components/PrepareSubmitPage.jsx
>        if (kommaseparertVedleggsliste) {
Bruk følgende kode fra slack:
 if (vedleggsIder.length > 0) {
        url = url.concat("&vedleggsIder=", vedleggsIder.join(','));
      }

2020-10-28 11:55 UTC, wen7i requested changes
endre kode og lager noe test

2020-10-28 23:39 UTC, 7er commented
Ja!

On Wed, Oct 28, 2020 at 12:50 PM sisselfladby <notifications@github.com>
wrote:

> *@sisselfladby* approved this pull request.
>
> Fint dette! Burde vi hatt en test her kanskje? :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/navikt/skjemautfylling-formio/pull/79#pullrequestreview-518578492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFT4ZGLIR5SJW6PBIAQQY3SNAAPRANCNFSM4TCGOXAQ>
> .
>

2020-10-29 14:39 UTC, it-vegard approved these changes

2020-10-29 14:41 UTC, wen7i approved these changes
💯

2020-10-29 14:42 UTC, merged